name: Basic Template
highlighter: pygments
safe: false
baseurl: /basic-template2
exclude: [morea]
morea_theme: spacelab
morea_google_analytics_tracking_id: "UA-61448657-1"
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule